# Generated by Django 3.0.6 on 2020-05-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tip',
            field=models.CharField(max_length=20),
        ),
    ]
