# Generated by Django 3.0.6 on 2020-05-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0003_tv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='cena',
            field=models.IntegerField(blank=True),
        ),
    ]
