# Generated by Django 3.0.6 on 2020-05-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0005_auto_20200516_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='napomena',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='cena_na_popustu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dijagonala',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dostupno',
            field=models.BooleanField(default=True),
        ),
    ]
