# Generated by Django 3.0.6 on 2020-05-16 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0006_auto_20200516_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='boja',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dimenzije',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dodatne_prednosti',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dvb_c',
            field=models.CharField(blank=True, default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dvb_s2',
            field=models.CharField(blank=True, default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='tv',
            name='dvb_t2',
            field=models.CharField(blank=True, default='Ne', max_length=5),
        ),
        migrations.AlterField(
            model_name='tv',
            name='ekran',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='energetski_razred',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='tv',
            name='masa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='napomena',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='ostalo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='povezivanje',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='tv',
            name='rezolucija',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tv',
            name='slike',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='tv',
            name='smart',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='tv',
            name='tip_tunera',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='vesa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tv',
            name='wireless',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tv',
            name='zvucnici',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('komentar', models.CharField(blank=True, max_length=500)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVStore_API.TV')),
            ],
        ),
    ]
