# Generated by Django 3.0.6 on 2020-05-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0007_auto_20200516_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='tv',
            new_name='ean',
        ),
    ]
