# Generated by Django 3.0.6 on 2020-05-17 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0008_auto_20200517_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porudzbina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=50)),
                ('broj', models.CharField(max_length=10)),
                ('grad', models.CharField(max_length=50)),
                ('postanski_broj', models.CharField(max_length=10)),
                ('telefon', models.CharField(max_length=20)),
                ('datumPorudzbine', models.DateField()),
                ('zavrsenaPoruzbina', models.BooleanField()),
                ('nacinPlacanja', models.CharField(max_length=50)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NaruceniArtikl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('ean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVStore_API.TV')),
                ('id_porudzbine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TVStore_API.Porudzbina')),
            ],
        ),
    ]
