# Generated by Django 3.0.8 on 2020-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVStore_API', '0011_auto_20200805_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='porudzbina',
            name='maticni_broj_firme',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='naziv_firme',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='pib',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='porudzbina',
            name='tip',
            field=models.CharField(default='fizicko', max_length=20),
        ),
    ]
