### Registration
POST http://127.0.0.1:8000/auth/registration/ HTTP/1.1
Content-Type: application/json

{
    "username": "test3",
    "password1": "test1234.",
    "password2": "test1234.",
    "email": "test3@test.com"  
}

### Login
POST http://127.0.0.1:8000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@test.com",   
    "password": "test1234."
}

### Me
GET http://127.0.0.1:8000/api/me/ HTTP/1.1
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

### Me PUT
PUT http://127.0.0.1:8000/api/me/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

{
    "tip": "fizicko",
    "pib": "234234234",
    "maticni_broj_firme": "123123",
    "username": "test5"
}



### Ocena GET
GET http://127.0.0.1:8000/api/ocena/8806098550340 HTTP/1.1
Content-Type: application/json


### Ocena POST
POST http://127.0.0.1:8000/api/ocena/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

{
    "ocena": 5,
    "komentar": "Mnogo dobar TV",
    "ean": "8806098550340"
}

### TV get
GET http://127.0.0.1:8000/api/tv/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

### GET poruzbinu
GET http://127.0.0.1:8000/api/porudzbina/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

### Posalji poruzbinu
POST http://127.0.0.1:8000/api/porudzbina/ HTTP/1.1
Content-Type: application/json
Authorization: Token 5a489ed5e9209fe9070088dd477ae0567bc419c3

{
    "ulica": "test",
    "broj": "test",
    "grad": "test",
    "postanski_broj": "test",
    "telefon": "test",
    "datumPorudzbine": "test",
    "nacinPlacanja": "test",
    "artikli": [
        {
            "ean": "8806098550340",
            "kolicina": 2
        },
        {
            "ean": "8806098550340",
            "kolicina": 3
        },
        {
            "ean": "8806098550340",
            "kolicina": 1
        }
    ]
}


